In [1]:
import numpy as np

In [2]:
#1
def matrix_generate(rows, columns, type_ = "full", eps = 0):
    A = None

    if type_ == "full":
        A = np.random.random(size=(rows, columns))

    elif type_ == "upper_triangular":
        A = np.triu(np.random.random(size=(rows, columns)))

    elif type_ == "lower_triangular":
        A = np.tril(np.random.random(size=(rows, columns)))
    
    elif type_ == "symmetric":
        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"
        else:
            A = np.random.random(size=(rows, columns))
            A = (A + A.T) / 2

    elif type_ == "diagonal":
        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"
        else:
            A = np.diag(np.random.random(size=rows))

    elif type_ == "perturbation":
        A = np.random.uniform(-eps, eps, size=(rows, columns))
        

    else:
        return f"Error with type {type_} and shape ({rows},{columns})"

    return A

In [3]:
matrix_generate(1, 3)

array([[0.14743477, 0.51232656, 0.6056124 ]])

In [4]:
matrix_generate(4, 4, type_ = "diagonal")

array([[0.66585638, 0.        , 0.        , 0.        ],
       [0.        , 0.99177994, 0.        , 0.        ],
       [0.        , 0.        , 0.11553599, 0.        ],
       [0.        , 0.        , 0.        , 0.06730484]])

In [5]:
matrix_generate(4, 4, type_ = "upper_triangular")

array([[0.36660221, 0.1871357 , 0.05753864, 0.29788929],
       [0.        , 0.25963301, 0.44058764, 0.4223806 ],
       [0.        , 0.        , 0.68442298, 0.59849211],
       [0.        , 0.        , 0.        , 0.42742245]])

In [6]:
matrix_generate(4, 4, type_ = "lower_triangular")

array([[0.44963063, 0.        , 0.        , 0.        ],
       [0.14410084, 0.16174256, 0.        , 0.        ],
       [0.8513568 , 0.72669427, 0.31576201, 0.        ],
       [0.04329303, 0.42034317, 0.45802351, 0.68526889]])

In [7]:
matrix_generate(4, 4, type_ = "symmetric")

array([[0.29762084, 0.47318175, 0.4972501 , 0.53369823],
       [0.47318175, 0.93449132, 0.0320516 , 0.38918119],
       [0.4972501 , 0.0320516 , 0.04357956, 0.50443611],
       [0.53369823, 0.38918119, 0.50443611, 0.87949022]])

In [8]:
matrix_generate(4, 1, type_ = "symmetric")

'Error with type symmetric and shape (4,1)'

Теперь величину нормы матрицы возмущений в зависимости от параметра $\varepsilon$ (оценить верхную границу).



- __Норма Фробениуса__:  $\quad$   $||M||_F=\sqrt{\sum_{i=1}^n \sum_{j=1}^n\left|a_{i j}\right|^2} \leq \sqrt{nm} \varepsilon$

#### Задание 2. Вычисление матричных норм и числа обусловленности.

Реализовать вычисление трех основных норм векторов (L1, L2 и максимальную) и подчиненных им матричных норм. Реализовать вычисление числа обусловленности.

Примечание: для вычисления собственных значений можно использовать linalg.eigvals из модуля scipy.

In [9]:
import numpy as np
from scipy.linalg import eigvals, norm

def vector_norms(vector):
    l1_norm = np.sum(np.abs(vector))
    l2_norm = np.sqrt(np.sum(vector**2))
    max_norm = np.max(np.abs(vector))
    return l1_norm, l2_norm, max_norm

def matrix_norms(matrix):
    l1_matrix_norm = np.max(np.sum(np.abs(matrix), axis=1))
    l2_matrix_norm = np.max(eigvals(matrix.T @ matrix)) ** 0.5
    max_matrix_norm = np.max(np.sum(np.abs(matrix), axis=0))
    return l1_matrix_norm, l2_matrix_norm, max_matrix_norm

def condition_number(matrix):
    eigenvalues = eigvals(matrix)
    max_eigenvalue = np.max(np.abs(eigenvalues))
    min_eigenvalue = np.min(np.abs(eigenvalues))
    return max_eigenvalue / min_eigenvalue




# Пример использования
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2], [3, 4]])

l1_norm, l2_norm, max_norm = vector_norms(vector)
print(f"L1 norm: {l1_norm}, L2 norm: {l2_norm}, Max norm: {max_norm}")

l1_matrix_norm, l2_matrix_norm, max_matrix_norm = matrix_norms(matrix)
print(f"L1 matrix norm: {l1_matrix_norm}, L2 matrix norm: {l2_matrix_norm}, Max matrix norm: {max_matrix_norm}")

cond_num = condition_number(matrix)
print(f"Condition number: {cond_num}")

L1 norm: 6, L2 norm: 3.7416573867739413, Max norm: 3
L1 matrix norm: 7, L2 matrix norm: (5.464985704219043+0j), Max matrix norm: 6
Condition number: 14.430703308172536


### 3

$||\mathbf{x}||_1 = \left( \sum_{i=1}^{n} |x_i| \right) >= 1/\sqrt{n} \left( \sum_{i=1}^{n} x_i^2 \right)^{1/2} = 1/\sqrt{n} ||\mathbf{x}||_2.$


Отсюда:


$||\mathbf{x}||_1 >= 1/\sqrt{n} ||\mathbf{x}||_2,$


то есть  C_2 = 1/$\sqrt{n} .$

Для $\ C_1||\mathbf{x}||_2 >= ||\mathbf{x}||_1$

подойдет $С_1 = 1$, тк квадрат с диагональю 2 можно вписать в круг с диаметром 2


### 4

**1. Неравенство** $||x||_2 \leq \sqrt{m} \cdot ||x||_{\infty}$

***Доказательство:***

Воспользуемся определением норм. Пусть $x = (x_1, x_2, \ldots, x_m)$.

- Норма $\ell_2$:
  $ ||x||_2 = \sqrt{x_1^2 + x_2^2 + \ldots + x_m^2} $

- Норма $\ell_{\infty}$:
  $ ||x||_{\infty} = \max_{1 \leq i \leq m} |x_i| $

Пусть $M = ||x||_{\infty}$. Тогда $|x_i| \leq M \quad \forall i$, значит:
$ x_1^2 + x_2^2 + \ldots + x_m^2 \leq m M^2 $

Следовательно:
$ ||x||_2 = \sqrt{x_1^2 + x_2^2 + \ldots + x_m^2} \leq \sqrt{m M^2} = \sqrt{m} \cdot ||x||_{\infty} $

Таким образом:
$ ||x||_2 \leq \sqrt{m} \cdot ||x||_{\infty} $

***Пример:***

Рассмотрим вектор $x = (1, 1, \ldots, 1)$ размерности $m$. В этом случае:
$ ||x||_2 = \sqrt{m} \quad \text{и} \quad ||x||_{\infty} = 1 $  
Подставляя в неравенство, получаем:  
$ ||x||_2 = \sqrt{m} \leq \sqrt{m} \cdot 1 $  
что дает равенство $||x||_2 = \sqrt{m} \cdot ||x||_{\infty}$.

**2. Неравенство** $||A||_{\infty} \leq \sqrt{n} \cdot ||A||_2$

***Доказательство:***

Из теории и матанализа нам известно, что:  
$ ||A||_{\infty} = \sup_{x \neq 0} \dfrac{||Ax||_{\infty}}{||x||_{\infty}} \leq \sup_{x \neq 0} \dfrac{||Ax||_{\infty}}{\dfrac{1}{\sqrt{n}}||x||_{2}} \leq \sup_{x \neq 0} \dfrac{\sqrt{n} \cdot ||Ax||_{2}}{\sqrt{m} \cdot ||x||_{2}} \leq \sqrt{n} \cdot ||A||_{2}$

Откуда:
$ ||A||_{\infty} \leq \sqrt{n} \cdot ||A||_2 $  

***Пример:***

Рассмотрим матрицу $A = \begin{pmatrix} 1 & 1 & 1 & \dots & 1 \\ 0 & \dots & \dots & \dots & 0 \\ \vdots & \vdots & \vdots & \vdots & \vdots \\ 0 & \dots & \dots & \dots & 0 \end{pmatrix}$ размерности $m \times n$. В этом случае:
- Норма $||A||_{\infty} = n$.  
- Норма $||A||_2 = \sqrt{n}$.

Таким образом, получаем:
$ ||A||_{\infty} = n = \sqrt{n} \cdot \sqrt{n} = \sqrt{n} \cdot ||A||_{2}$.  

____________________

### 5

$||\mathbf{A}||_{F}^{2}=\operatorname{tr} (\mathbf{A}^{+} \mathbf{A}) = \operatorname{tr} (\mathbf{A} \mathbf{A}^{+})$  

$||\mathbf{UA}||_{F}^{2}=\operatorname{tr} (\mathbf{A}^{+} \mathbf{U}^{+} \mathbf{U} \mathbf{A} ) = \operatorname{tr} (\mathbf{A}^{+} \mathbf{A}) = ||\mathbf{A}||_{F}^{2}$  

$||\mathbf{AU}||_{F}^{2}=\operatorname{tr} (\mathbf{A} \mathbf{U} \mathbf{U}^{+} \mathbf{A}^{+}) = \operatorname{tr} (\mathbf{A} \mathbf{A}^{+}) = ||\mathbf{A}||_{F}^{2}$  
